### PR TITLE
add import to python subdocument example

### PR DESCRIPTION
**Pull request by steveyen**
Not sure if this will do what I think it'll do, but wanting to add a import to the example so the reader doesn't have to dig around.

### CODE REVIEW

**Review by ingenthr — CHANGES_REQUESTED** [review]
Unfortunately, this is, I think, not correct syntactically.  If you are using tagging as shown on line 73, the whole code sample should be in the tag.  You can fix this by adding it to the sample code in the tag block.

Line 73 refers to: https://github.com/couchbase/docs-sdk-python/blob/release/3.0/modules/howtos/examples/subdocument_ops.py#L71-L75

Am I right about this @RichardSmedley?

I know it's slightly annoying with not having the code directly inline, but we get a benefit in being able to test the code against every release by including it with tagging.

**Comment by ingenthr** [comment]
@griels or @davidkelly can you comment on the correctness of the import in this code sample?

**Comment by griels** [comment]
The import is fine, and will show up in the rendered document as intended, but we might as well just move the tags to include the import that is already present in the Python file. We can do this for subsequent imports of the same thing, should that be considered illustrative for other examples in the same Python file - it will show up as a redundant import in PyCharm etc, but it will still work and keep all the Python code in one place.

Generally it is better to keep all the Python code in our runnable samples, so that we can run CI etc on them and ensure the syntax is correct, as Matt indicates.

**Review by RichardSmedley — APPROVED** [review]
LGTM - thanks @steveyen @griels

**Review by griels — APPROVED** [review]

**Review by griels — APPROVED** [review]

**Review by ingenthr — APPROVED** [review]
Thanks for the update

**Pull request merged**
